#!/bin/sh

### BEGIN INIT INFO
# Provides:          ba-pwd-updater
# Required-Start:    $local_fs $remote_fs $network $syslog $time
# Required-Stop:     $local_fs $remote_fs $network $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop Basic Authentication Password Updater daemon
# Description:       Start or stop Basic Authentication Password Updater daemon
### END INIT INFO

set -e

BA_PWD_UPDATER_ROOT="/home/sysadmin/ba-pwd-updater"

case "$1" in
  start)
    cat ${BA_PWD_UPDATER_ROOT}/PID | xargs kill || true
    python ${BA_PWD_UPDATER_ROOT}/app.py &
    echo $! > ${BA_PWD_UPDATER_ROOT}/PID
    ;;
  stop)
    cat ${BA_PWD_UPDATER_ROOT}/PID | xargs kill
    ;;
  *) echo "Usage: $0 {start|stop}" >&2; exit 1 ;;
esac

exit 0
