#!/bin/sh

### BEGIN INIT INFO
# Provides:          virsh
# Required-Stop:     $local_fs $remote_fs $network $syslog $time
# Default-Stop:      0 1 6
# Short-Description: Stop vm
# Description:       Stop vm
### END INIT INFO

set -e

VIRSH="/usr/bin/virsh"

case "$1" in
  stop)
    $VIRSH shutdown x16-vm
    ;;
  *) echo "Usage: $0 stop" >&2; exit 1 ;;
esac

exit 0
